// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx_d-ZipM6OaHL1hBUelIccqBxd9pDzOc',
    appId: '1:696817423498:web:29d31c832f7d32611d8973',
    messagingSenderId: '696817423498',
    projectId: 'focusnflow-f83a1',
    authDomain: 'focusnflow-f83a1.firebaseapp.com',
    storageBucket: 'focusnflow-f83a1.firebasestorage.app',
    measurementId: 'G-5D46M81GDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4x_FPnseCiJZbNX8xp69lpr22QNeqHOE',
    appId: '1:696817423498:android:8addecaf5b0592181d8973',
    messagingSenderId: '696817423498',
    projectId: 'focusnflow-f83a1',
    storageBucket: 'focusnflow-f83a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5IlEYo-LeiDJLSIxjhhx9KmgPrsEuxSU',
    appId: '1:696817423498:ios:e60ad5c13d107dd51d8973',
    messagingSenderId: '696817423498',
    projectId: 'focusnflow-f83a1',
    storageBucket: 'focusnflow-f83a1.firebasestorage.app',
    iosBundleId: 'com.example.focusFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5IlEYo-LeiDJLSIxjhhx9KmgPrsEuxSU',
    appId: '1:696817423498:ios:e60ad5c13d107dd51d8973',
    messagingSenderId: '696817423498',
    projectId: 'focusnflow-f83a1',
    storageBucket: 'focusnflow-f83a1.firebasestorage.app',
    iosBundleId: 'com.example.focusFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx_d-ZipM6OaHL1hBUelIccqBxd9pDzOc',
    appId: '1:696817423498:web:28e275370ecf94eb1d8973',
    messagingSenderId: '696817423498',
    projectId: 'focusnflow-f83a1',
    authDomain: 'focusnflow-f83a1.firebaseapp.com',
    storageBucket: 'focusnflow-f83a1.firebasestorage.app',
    measurementId: 'G-WLGK4D9K1W',
  );
}
