import 'package:focusnflow/models/study_room.dart';
import 'package:focusnflow/models/study_group.dart';

class SeedData {
  static final List<StudyRoom> gsuStudyRooms = [
    StudyRoom(
      id: 'room_1',
      name: 'Science Library - Study Zone 1',
      building: 'Science Library',
      roomNumber: '101',
      capacity: 10,
      currentOccupancy: 5,
      amenities: ['WiFi', 'Whiteboard', 'Outlets', 'Quiet'],
      latitude: 33.7490,
      longitude: -84.3880,
      isAvailable: true,
      lastUpdated: DateTime.now(),
    ),
    StudyRoom(
      id: 'room_2',
      name: 'Science Library - Group Room A',
      building: 'Science Library',
      roomNumber: '201A',
      capacity: 6,
      currentOccupancy: 3,
      amenities: ['WiFi', 'Whiteboard', 'Projector', 'Outlets'],
      latitude: 33.7490,
      longitude: -84.3880,
      isAvailable: true,
      lastUpdated: DateTime.now(),
    ),
    StudyRoom(
      id: 'room_3',
      name: 'University Center - Study Lounge',
      building: 'University Center',
      roomNumber: '305',
      capacity: 20,
      currentOccupancy: 18,
      amenities: ['WiFi', 'Outlets'],
      latitude: 33.7510,
      longitude: -84.3890,
      isAvailable: true,
      lastUpdated: DateTime.now(),
    ),
    StudyRoom(
      id: 'room_4',
      name: 'College of Engineering - Lab Room',
      building: 'Engineering Building',
      roomNumber: '110',
      capacity: 8,
      currentOccupancy: 2,
      amenities: ['WiFi', 'Whiteboard', 'Projector', 'Outlets', 'Quiet'],
      latitude: 33.7480,
      longitude: -84.3900,
      isAvailable: true,
      lastUpdated: DateTime.now(),
    ),
    StudyRoom(
      id: 'room_5',
      name: 'Business School - Case Study Room',
      building: 'Business Building',
      roomNumber: '215',
      capacity: 12,
      currentOccupancy: 7,
      amenities: ['WiFi', 'Whiteboard', 'Projector'],
      latitude: 33.7520,
      longitude: -84.3870,
      isAvailable: true,
      lastUpdated: DateTime.now(),
    ),
    StudyRoom(
      id: 'room_6',
      name: 'Library South - Quiet Study',
      building: 'Library South',
      roomNumber: 'Ground',
      capacity: 15,
      currentOccupancy: 8,
      amenities: ['WiFi', 'Outlets', 'Quiet'],
      latitude: 33.7470,
      longitude: -84.3885,
      isAvailable: true,
      lastUpdated: DateTime.now(),
    ),
    StudyRoom(
      id: 'room_7',
      name: 'Tech Hub - Collaborative Space',
      building: 'Tech Hub',
      roomNumber: '3rd Floor',
      capacity: 25,
      currentOccupancy: 22,
      amenities: ['WiFi', 'Whiteboard', 'Projector', 'Outlets'],
      latitude: 33.7505,
      longitude: -84.3875,
      isAvailable: true,
      lastUpdated: DateTime.now(),
    ),
    StudyRoom(
      id: 'room_8',
      name: 'Arts Building - Creative Studio',
      building: 'Arts Building',
      roomNumber: '405',
      capacity: 10,
      currentOccupancy: 0,
      amenities: ['WiFi', 'Outlets'],
      latitude: 33.7495,
      longitude: -84.3895,
      isAvailable: true,
      lastUpdated: DateTime.now(),
    ),
  ];

  static final List<StudyGroup> gsuStudyGroups = [
      StudyGroup(
        id: 'group1',
        name: 'CS 2331 Algorithms Study Group',
        courseId: 'cs2331',
        courseName: 'CS 2331',
        description: 'Focused on algorithm design and analysis. Weekly problem-solving sessions.',
        adminId: 'user1',
        memberIds: ['user1', 'user2', 'user3'],
        maxMembers: 6,
        isPublic: true,
        createdAt: DateTime.now().subtract(Duration(days: 7)),
      ),
      StudyGroup(
        id: 'group2',
        name: 'MATH 2401 Calculus II Group',
        courseId: 'math2401',
        courseName: 'MATH 2401',
        description: 'Calculus II problem sets and exam prep. Help each other understand proofs.',
        adminId: 'user4',
        memberIds: ['user4', 'user5', 'user6', 'user7'],
        maxMembers: 8,
        isPublic: true,
        createdAt: DateTime.now().subtract(Duration(days: 14)),
      ),
      StudyGroup(
        id: 'group3',
        name: 'PHYS 2211 Physics Study',
        courseId: 'phys2211',
        courseName: 'PHYS 2211',
        description: 'Physics I mechanics and waves. Lab report collaboration.',
        adminId: 'user8',
        memberIds: ['user8', 'user9'],
        maxMembers: 5,
        isPublic: true,
        createdAt: DateTime.now().subtract(Duration(days: 3)),
      ),
      StudyGroup(
        id: 'group4',
        name: 'ENG 1101 Writing Center Group',
        courseId: 'eng1101',
        courseName: 'ENG 1101',
        description: 'Essay review and writing feedback. Peer editing sessions Tuesday & Thursday.',
        adminId: 'user10',
        memberIds: ['user10', 'user11', 'user12', 'user13', 'user14'],
        maxMembers: 6,
        isPublic: true,
        createdAt: DateTime.now().subtract(Duration(days: 21)),
      ),
      StudyGroup(
        id: 'group5',
        name: 'CHEM 1211 Lab Partners',
        courseId: 'chem1211',
        courseName: 'CHEM 1211',
        description: 'General Chemistry I lab preparation and data analysis.',
        adminId: 'user15',
        memberIds: ['user15', 'user16', 'user17', 'user18', 'user19', 'user20'],
        maxMembers: 6,
        isPublic: false,
        createdAt: DateTime.now().subtract(Duration(days: 10)),
      ),
      StudyGroup(
        id: 'group6',
        name: 'BIO 2107 Exam Cram',
        courseId: 'bio2107',
        courseName: 'BIO 2107',
        description: 'Biology II midterm prep. Focus on cellular biology and genetics.',
        adminId: 'user21',
        memberIds: ['user21', 'user22', 'user23'],
        maxMembers: 8,
        isPublic: true,
        createdAt: DateTime.now().subtract(Duration(days: 2)),
      ),
      StudyGroup(
        id: 'group7',
        name: 'PSY 1101 Case Studies',
        courseId: 'psy1101',
        courseName: 'PSY 1101',
        description: 'Intro to Psychology case study analysis and discussion.',
        adminId: 'user24',
        memberIds: ['user24', 'user25'],
        maxMembers: 10,
        isPublic: true,
        createdAt: DateTime.now().subtract(Duration(days: 5)),
      ),
      StudyGroup(
        id: 'group8',
        name: 'HIST 1111 Timeline Masters',
        courseId: 'hist1111',
        courseName: 'HIST 1111',
        description: 'World History timeline events and their connections.',
        adminId: 'user26',
        memberIds: ['user26', 'user27', 'user28', 'user29'],
        maxMembers: 8,
        isPublic: true,
        createdAt: DateTime.now().subtract(Duration(days: 11)),
      ),
    ];
}
